language: php

sudo: false
dist: xenial
os: linux

services:
    - mysql

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - DATABASE_URL=mysql://root:@127.0.0.1:3306/unite_test

matrix:
    include:
        - php: 7.2

before_install:
    - |
        mysql -e 'CREATE DATABASE unite_test;'

install:
    - composer install

script:
    - ./vendor/phpunit/phpunit/phpunit
