language: php

sudo: false
dist: xenial
os: linux

services:
    - mysql

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
    include:
        - php: 7.2

install:
    - composer install

script:
    - ./vendor/phpunit/phpunit/phpunit
