unite_cms_core_api:
    path: /{unite_domain}
    methods: [POST, OPTIONS]
    controller: UniteCMS\CoreBundle\Controller\ApiController::api
    defaults:
        unite_domain: 'default'

unite_cms_admin:
    path: /{unite_domain}
    methods: [GET]
    controller: UniteCMS\AdminBundle\Controller\AdminController::app
    defaults:
        unite_domain: 'default'
