
# Create services based on arguments
services:

    unite.cms_core.graphql.provider.unite_cms:
        parent: UniteCMS\CoreBundle\GraphQL\Schema\Provider\SchemaFileProvider
        arguments: ['%kernel.project_dir%/vendor/unite-cms/core-bundle/Resources/GraphQL/Schema/unite-cms.graphql']
        tags: ['unite.graphql.schema_provider']
